"""This module contains classes of graphoelements.

These graphoelements can be generated by the package "detect".

"""


class Ripple:
    def __init__(self):
        pass


class SlowWave:
    def __init__(self):
        pass

class Spindles:
    """Class containing all the spindles in one dataset.

    Attributes
    ----------
    chan_name : ndarray (dtype='U')
        list of channels


    """
    def __init__(self):
        self.chan_name = None
        self.spindle = []
        one_spindle = {'start': None,
                       'end': None,
                       'chan': [],
                       }
        self.spindle.append(one_spindle)