"""This module contains classes of graphoelements.

These graphoelements can be generated by the package "detect".

"""


class Ripple:
    def __init__(self):
        pass


class SlowWave:
    def __init__(self):
        pass


class Spindle:
    def __init__(self):
        pass
